title: rhys-the-davies
email: rhys.michael.davies@gmail.com
name: rhys-the-davies

description: Blogging about stuff and things
meta_description: "rhys-the-davies' blog site for all things"

twitter_username: rhys_the_davies
github_username:  rhys-the-davies

author: Rhys Davies
linkedin_username: rhys-the-davies

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /myblog
domain_name: "https://github.com/rhys-the-davies"
google_analytics: "UA-XXXXXXXX-X"


plugins: 
  - jekyll-feed
  - jekyll-paginate

# Details for the RSS feed generator
url: ""
copyright: "rhys-the-davies"

# Disqus config
disqus-shortname: ""
